
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 03 18:57:38 COT 2020
//----------------------------------------------------

package com.company;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int pc = 16;
  public static final int para = 26;
  public static final int finpara = 27;
  public static final int com = 24;
  public static final int mientras = 13;
  public static final int sino = 22;
  public static final int finsi = 20;
  public static final int hacer = 14;
  public static final int num = 2;
  public static final int Programa = 17;
  public static final int ol = 11;
  public static final int real = 3;
  public static final int EOF = 0;
  public static final int FinPrograma = 18;
  public static final int asig = 7;
  public static final int id = 8;
  public static final int escribir = 30;
  public static final int entonces = 21;
  public static final int op_aritmetico = 4;
  public static final int hasta = 28;
  public static final int op_relacional = 5;
  public static final int pal = 25;
  public static final int str = 12;
  public static final int error = 1;
  public static final int finmientras = 15;
  public static final int ent = 23;
  public static final int op_incremento = 6;
  public static final int pi = 9;
  public static final int leer = 29;
  public static final int si = 19;
  public static final int pd = 10;
}

